const mockNeighborhoodData = [
  {
    Id: 1,
    propertyId: 1,
    schoolRating: 8.5,
    elementaryRating: 9,
    middleSchoolRating: 8,
    highSchoolRating: 8,
    transitScore: 85,
    busRoutes: 12,
    nearestStation: "0.3 mi",
    avgWaitTime: 8,
    walkScore: 92,
    nearbyRestaurants: 45,
    nearbyGrocery: 8,
    nearbyParks: 6
  },
  {
    Id: 2,
    propertyId: 2,
    schoolRating: 7.8,
    elementaryRating: 8,
    middleSchoolRating: 7,
    highSchoolRating: 8,
    transitScore: 72,
    busRoutes: 8,
    nearestStation: "0.5 mi",
    avgWaitTime: 12,
    walkScore: 85,
    nearbyRestaurants: 32,
    nearbyGrocery: 6,
    nearbyParks: 8
  },
  {
    Id: 3,
    propertyId: 3,
    schoolRating: 9.2,
    elementaryRating: 9,
    middleSchoolRating: 9,
    highSchoolRating: 10,
    transitScore: 78,
    busRoutes: 10,
    nearestStation: "0.4 mi",
    avgWaitTime: 10,
    walkScore: 88,
    nearbyRestaurants: 38,
    nearbyGrocery: 7,
    nearbyParks: 5
  },
  {
    Id: 4,
    propertyId: 4,
    schoolRating: 9.5,
    elementaryRating: 10,
    middleSchoolRating: 9,
    highSchoolRating: 9,
    transitScore: 65,
    busRoutes: 6,
    nearestStation: "0.8 mi",
    avgWaitTime: 15,
    walkScore: 70,
    nearbyRestaurants: 18,
    nearbyGrocery: 4,
    nearbyParks: 12
  },
  {
    Id: 5,
    propertyId: 5,
    schoolRating: 7.2,
    elementaryRating: 7,
    middleSchoolRating: 7,
    highSchoolRating: 8,
    transitScore: 68,
    busRoutes: 7,
    nearestStation: "0.6 mi",
    avgWaitTime: 14,
    walkScore: 75,
    nearbyRestaurants: 22,
    nearbyGrocery: 5,
    nearbyParks: 9
  }
]

export default mockNeighborhoodData